services:
  server:
    restart: always
    build:
      context: ../..
      dockerfile: src/waqd_website/Dockerfile
    image: waqd/waqd_website:latest
    container_name: waqd_website
    environment:
      DATABASE_PW: waqd_root_pw
      MARIADB_URL: mariadb:3306
    ports:
      - "80:8080"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: waqd_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: waqd_root_pw
      MYSQL_DATABASE: waqd_userdata
      # MYSQL_USER: waqd_user
      # MYSQL_PASSWORD: waqd_user_pw
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
