services:
  server:
    restart: always
    build:
      context: ../..
      dockerfile: src/waqd_website/Dockerfile
    image: waqd/waqd_website:latest
    container_name: waqd_website
    environment:
      DATABASE_PW: waqd_root_pw
      POSTGRES_URL: postgres:5430
    ports:
      - "80:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: waqd_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: waqd_root_pw
      POSTGRES_DB: waqd_userdata

    ports:
      - "3306:3306"
    volumes:
      - postgres_data:/var/lib/mysql

volumes:
  postgres_data:
    driver: local
